### ISSUE TITLE
ContentControl. insertTable method throw an error 

### ISSUE THREAD

**Issue by nisharamj** [OfficeDev/office-js-docs#631]
I am trying to insert a table into content control object using word api 1.3. I have updated word to uptodate(it is version 1609 build 7369.2055) and I am using https://appsforoffice.microsoft.com/lib/beta/hosted/office.js. But then I got an error as below.
`ItemNotFound: ItemNotFound
   at Anonymous function (https://appsforoffice.microsoft.com/lib/beta/hosted/word-win32-16.01.js:19:188232)
   at pi (https://appsforoffice.microsoft.com/lib/beta/hosted/word-win32-16.01.js:19:210600)
   at ht (https://appsforoffice.microsoft.com/lib/beta/hosted/word-win32-16.01.js:19:210687)
   at g (https://appsforoffice.microsoft.com/lib/beta/hosted/word-win32-16.01.js:19:210507)
   at l (https://appsforoffice.microsoft.com/lib/beta/hosted/word-win32-16.01.js:19:209093)`

Can anyone help me to solve this problem please?

**Comment by kbrandl** [comment]
@nisharamj apologies for the lack of response on this. Are you still having trouble? The Office.js API and platform has evolved quite a bit since this issue was opened, so this may no longer be an issue. I'm going to close this issue, but please feel free to re-open it or log a new issue in the [OfficeDev/office-js](https://github.com/OfficeDev/office-js) repo if you're still having trouble.
